targets:
  $default:
    builders:
      flutter_cms|cmsBuilder:
        enabled: true

builders:
  cmsBuilder:
    target: ":flutter_cms"
    import: "package:flutter_cms/src/generators/builder.dart"
    builder_factories: ["cmsBuilder"]
    build_extensions: {".dart": [".cms.g.dart"]}
    auto_apply: dependents
    build_to: source
    # To copy the `.g.part` content into `.g.dart` in the source tree
    applies_builders: ["source_gen:combining_builder"]
    