builders:
  cmsBuilder:
    target: ":flutter_cms_generator"
    import: "package:flutter_cms_generator/flutter_cms_generator.dart"
    builder_factories: ["cmsBuilder"]
    build_extensions: {".dart": [".cms.g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
